language: python
python:
    - 3.6

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7

before_install:
    - pip3 install coveralls
    - git clone https://github.com/tschijnmo/DummyRDD.git
    - cd DummyRDD; python3 setup.py install; cd ..
install:
    - export CC=gcc-7
    - export CXX=g++-7
    - python3 setup.py install

script:
    - export DUMMY_SPARK=1
    - cd tests
    - coverage run --source=drudge -m pytest -sv

after_success:
  - coveralls

