theme: minima

title: Drudge / Gristmill
author: Jinmo Zhao
email: tschijnmotschau@gmail.com
github_username: tschijnmo
description: >
    Symbolic tensor and non-commutative algebra with powerful automatic code
    generation and optimization

include: ['_static']

header_pages: ['install.md', 'docs.md', 'news.html']
